version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_NAME=movies

  db:
    image: postgres
    ports:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
